# Workflow to build rpm and deb packages

name: packaging deb and rpm

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GH_TOKEN: ${{ secrets.GITHUB_Token }}
  upload_url: ${{ github.event.release.upload_url }}
  release_message: ${{ github.event.release.body }}
  tag: ${{ github.ref_name }}

jobs:
  deb_job:
    name: create .deb asset for release
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create .deb file
        run: bash ./Installer/createPackage/deb.sh $tag $release_message

      - name: uploade .deb file to assets
        run: gh release upload $tag AuditTAP-$tag.deb --clobber
      
      - name: cleanup
        run: rm AuditTAP-$tag.deb
  
  rpm_job:
    name: create .rpm asset for release
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create .rpm file
        run: bash ./Installer/createPackage/rpm.sh $tag $release_message

      - name: uploade .rpm file to assets
        run: gh release upload $tag AuditTAP-$tag.rpm --clobber
      
      - name: cleanup
        run: rm AuditTAP-$tag.rpm
  
  setup_job:
    name: upload windows installer
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: upload setup.exe
        run: |
          cp Installer/setup.exe ./AuditTAP-$tag-windows-installer.exe
          gh release upload $tag AuditTAP-$tag-windows-installer.exe --clobber
          rm AuditTAP-$tag-windows-installer.exe